server:
  port: ${CUSTOM.SERVER.PORT:9004}

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      # username: larh
      # password: larh
      database: larhdb
      # uri: mongodb://larh:larh@localhost:27017/larhdb
      authentication-database: admin

encrypt:
  key: larh