server:
  port: ${CUSTOM.SERVER.PORT:9004}

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

# Configuracion de MongoDB para Spring 2.0
#spring:
  #data:
    #mongodb:
      #host: localhost
      #port: 27017
      # username: larh
      # password: larh
      #database: larhdb
      #uri: mongodb://larh:larh@localhost:27017/larhdb
      #authentication-database: admin

# Configuracion de MongoDB para Spring 3.0
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      # username: larh
      # password: larh
      database: larhdb
      uri: mongodb://larh:larh@localhost:27017/larhdb?authSource=admin

encrypt:
  key: larh